package manus

import "time"

// AvailableCreditsResponse wraps the response from GET /v2/usage.availableCredits.
type AvailableCreditsResponse struct {
	OK        bool             `json:"ok"`
	RequestID string           `json:"request_id,omitempty"`
	Data      AvailableCredits `json:"data"`
	Error     *APIError        `json:"error,omitempty"`
}

// AvailableCredits represents credit balance details from Manus API v2.
type AvailableCredits struct {
	TotalCredits      int    `json:"total_credits"`
	FreeCredits       int    `json:"free_credits"`
	PeriodicCredits   int    `json:"periodic_credits"`
	AddonCredits      int    `json:"addon_credits"`
	ProMonthlyCredits int    `json:"pro_monthly_credits"`
	EventCredits      int    `json:"event_credits"`
	RefreshCredits    int    `json:"refresh_credits"`
	MaxRefreshCredits int    `json:"max_refresh_credits"`
	NextRefreshTime   int64  `json:"next_refresh_time"`
	RefreshInterval   string `json:"refresh_interval"`
	CurrentPeriodEnd  int64  `json:"current_period_end"`
}

// NextRefreshTimeFormatted returns the next refresh time formatted as RFC3339.
func (c *AvailableCredits) NextRefreshTimeFormatted() string {
	if c.NextRefreshTime <= 0 {
		return "N/A"
	}
	return time.Unix(c.NextRefreshTime, 0).UTC().Format(time.RFC3339)
}

// CreateTaskRequest payload for POST /v2/task.create.
type CreateTaskRequest struct {
	Title            string                 `json:"title,omitempty"`
	Message          TaskMessageInput       `json:"message"`
	AgentProfile     string                 `json:"agent_profile,omitempty"`
	StructuredOutput map[string]interface{} `json:"structured_output,omitempty"`
	Connectors       []string               `json:"connectors,omitempty"`
	ProjectID        string                 `json:"project_id,omitempty"`
}

// TaskMessageInput message input for task.create or task.sendMessage.
type TaskMessageInput struct {
	Content     string   `json:"content"`
	Attachments []string `json:"attachments,omitempty"`
}

// CreateTaskResponse response from POST /v2/task.create.
type CreateTaskResponse struct {
	OK        bool           `json:"ok"`
	RequestID string         `json:"request_id,omitempty"`
	Data      CreateTaskData `json:"data"`
	Error     *APIError      `json:"error,omitempty"`
}

// CreateTaskData holds created task details.
type CreateTaskData struct {
	TaskID    string `json:"task_id"`
	TaskTitle string `json:"task_title,omitempty"`
	Status    string `json:"status,omitempty"`
}

// ListMessagesResponse response from GET /v2/task.listMessages.
type ListMessagesResponse struct {
	OK        bool             `json:"ok"`
	RequestID string           `json:"request_id,omitempty"`
	Data      ListMessagesData `json:"data"`
	Error     *APIError        `json:"error,omitempty"`
}

// ListMessagesData messages wrapper.
type ListMessagesData struct {
	Messages []TaskMessage `json:"messages"`
}

// TaskMessage item inside task.listMessages.
type TaskMessage struct {
	ID               string            `json:"id,omitempty"`
	Type             string            `json:"type"` // status_update, assistant_message, user_message
	StatusUpdate     *StatusUpdateData `json:"status_update,omitempty"`
	AssistantMessage *AssistantMessage `json:"assistant_message,omitempty"`
	CreatedAt        string            `json:"created_at,omitempty"`
}

// StatusUpdateData status event details.
type StatusUpdateData struct {
	AgentStatus string `json:"agent_status"` // running, stopped, waiting
}

// AssistantMessage content from Manus agent.
type AssistantMessage struct {
	Text        string       `json:"text,omitempty"`
	Content     string       `json:"content,omitempty"`
	Attachments []Attachment `json:"attachments,omitempty"`
}

// Body returns text or content if text is empty.
func (a *AssistantMessage) Body() string {
	if a.Text != "" {
		return a.Text
	}
	return a.Content
}

// Attachment file or URL artifact generated by the agent.
type Attachment struct {
	URL      string `json:"url"`
	Title    string `json:"title,omitempty"`
	MimeType string `json:"mime_type,omitempty"`
}

// TaskDetailResponse response from GET /v2/task.detail.
type TaskDetailResponse struct {
	OK        bool           `json:"ok"`
	RequestID string         `json:"request_id,omitempty"`
	Data      TaskDetailData `json:"data"`
	Error     *APIError      `json:"error,omitempty"`
}

// TaskDetailData full metadata of a task.
type TaskDetailData struct {
	ID        string `json:"id"`
	Title     string `json:"title,omitempty"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at,omitempty"`
	UpdatedAt int64  `json:"updated_at,omitempty"`
}

// StopTaskRequest payload for POST /v2/task.stop.
type StopTaskRequest struct {
	TaskID string `json:"task_id"`
}

// SendMessageRequest payload for POST /v2/task.sendMessage.
type SendMessageRequest struct {
	TaskID  string           `json:"task_id"`
	Message TaskMessageInput `json:"message"`
}

// StandardResponse generic response envelope.
type StandardResponse struct {
	OK        bool      `json:"ok"`
	RequestID string    `json:"request_id,omitempty"`
	Error     *APIError `json:"error,omitempty"`
}

// APIError standard error response format from Manus API.
type APIError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (e *APIError) Error() string {
	return e.Code + ": " + e.Message
}
